name: 3x Daily Dummy Commits

on:
  schedule:
    - cron: '0 4 * * *'   # 4 AM UTC
    - cron: '0 12 * * *'  # 12 PM UTC
    - cron: '0 20 * * *'  # 8 PM UTC
  workflow_dispatch:     # allows manual trigger if needed

jobs:
  dummy-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create Dummy Commit
        run: |
          git config user.name "meh-bot"
          git config user.email "meh-bot@example.com"
          date > dummy.txt
          git add dummy.txt
          git commit -m "🤖 dummy commit to trigger redeploy at $(date)"
          git push
